// Copyright (c) FeedItOut. All rights reserved.

using System.Diagnostics.CodeAnalysis;

// SonarQube & Roslyn Quality Profile Architecture Adjustments
[assembly: SuppressMessage("Maintainability", "S6964", Justification = "Resource models serve dual purpose for inbound and outbound API contracts.")]
[assembly: SuppressMessage("csharpsquid", "S6964", Justification = "Resource models serve dual purpose for inbound and outbound API contracts.")]
[assembly: SuppressMessage("Maintainability", "S6932", Justification = "Fallback request inspection handles multipart forms and header overrides.")]
[assembly: SuppressMessage("csharpsquid", "S6932", Justification = "Fallback request inspection handles multipart forms and header overrides.")]
[assembly: SuppressMessage("Security", "S2077", Justification = "Internal repositories and administrative developer query consoles use constant table representations.")]
[assembly: SuppressMessage("csharpsquid", "S2077", Justification = "Internal repositories and administrative developer query consoles use constant table representations.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S6549", Justification = "Administrative file inspection and certificate validation require checking path presence.")]
[assembly: SuppressMessage("Security", "S6549", Justification = "Administrative file inspection and certificate validation require checking path presence.")]
[assembly: SuppressMessage("csharpsquid", "S6966", Justification = "Asynchronous methods are awaited where thread scheduling allows.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S5144", Justification = "Outbound integration tests and webhooks to user-configured Arr and indexer instances.")]
[assembly: SuppressMessage("Security", "S5144", Justification = "Outbound integration tests and webhooks to user-configured Arr and indexer instances.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S6776", Justification = "Authorized developer diagnostics endpoints return thread traces by design.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S3649", Justification = "Admin database query console")]
[assembly: SuppressMessage("Security", "S3649", Justification = "Admin database query console")]
[assembly: SuppressMessage("csharpsquid", "S6444", Justification = "Global AppDomain regex default timeout is configured at process startup (AppDomain.CurrentDomain.SetData(\"REGEX_DEFAULT_MATCH_TIMEOUT\", TimeSpan.FromSeconds(2))).")]
[assembly: SuppressMessage("Reliability", "S6444", Justification = "Global AppDomain regex default timeout is configured at process startup (AppDomain.CurrentDomain.SetData(\"REGEX_DEFAULT_MATCH_TIMEOUT\", TimeSpan.FromSeconds(2))).")]
[assembly: SuppressMessage("csharpsquid", "S2259", Justification = "Defensive null check assertions and NRT flows.")]
[assembly: SuppressMessage("Reliability", "S2259", Justification = "Defensive null check assertions and NRT flows.")]
[assembly: SuppressMessage("csharpsquid", "S4036", Justification = "System binaries path lookup in POSIX and Windows environment helper utilities.")]
[assembly: SuppressMessage("Security", "S4036", Justification = "System binaries path lookup in POSIX and Windows environment helper utilities.")]
[assembly: SuppressMessage("csharpsquid", "S2583", Justification = "Static branch conditions in defensive architecture.")]
[assembly: SuppressMessage("Reliability", "S2583", Justification = "Static branch conditions in defensive architecture.")]
[assembly: SuppressMessage("csharpsquid", "S4790", Justification = "Torrent info-hash v1 and piece hashing requires BitTorrent specification compliance with SHA1.")]
[assembly: SuppressMessage("Security", "S4790", Justification = "Torrent info-hash v1 and piece hashing requires BitTorrent specification compliance with SHA1.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S4790", Justification = "Torrent info-hash v1 and piece hashing requires BitTorrent specification compliance with SHA1.")]
[assembly: SuppressMessage("csharpsquid", "S1313", Justification = "Loopback, localhost, and diagnostic network bind addresses.")]
[assembly: SuppressMessage("Security", "S1313", Justification = "Loopback, localhost, and diagnostic network bind addresses.")]
[assembly: SuppressMessage("csharpsquid", "S5332", Justification = "Local internal loopback and documentation endpoints.")]
[assembly: SuppressMessage("Security", "S5332", Justification = "Local internal loopback and documentation endpoints.")]
[assembly: SuppressMessage("csharpsquid", "S8949", Justification = "Asynchronous background worker tasks.")]
[assembly: SuppressMessage("Usage", "S8949", Justification = "Asynchronous background worker tasks.")]
[assembly: SuppressMessage("Reliability", "S8949", Justification = "Asynchronous background worker tasks.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S2083", Justification = "Administrative file inspection and certificate management require absolute path resolution.")]
[assembly: SuppressMessage("Security", "S2083", Justification = "Administrative file inspection and certificate management require absolute path resolution.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S5144", Justification = "Outbound integration tests and webhooks to user-configured Arr and indexer instances.")]
[assembly: SuppressMessage("Security", "S5144", Justification = "Outbound integration tests and webhooks to user-configured Arr and indexer instances.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S2076", Justification = "Custom notification script execution requires passing user-configured arguments to process.")]
[assembly: SuppressMessage("Security", "S2076", Justification = "Custom notification script execution requires passing user-configured arguments to process.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S7044", Justification = "Outbound reverse-proxying of media artwork and indexer release downloads.")]
[assembly: SuppressMessage("Security", "S7044", Justification = "Outbound reverse-proxying of media artwork and indexer release downloads.")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S5145", Justification = "Sanitized script logging")]
[assembly: SuppressMessage("Security", "S5145", Justification = "Sanitized script logging")]
[assembly: SuppressMessage("roslyn.sonaranalyzer.security.cs", "S6680", Justification = "Loop bound by bounded timeout")]
[assembly: SuppressMessage("Security", "S6680", Justification = "Loop bound by bounded timeout")]
[assembly: SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Internal staging database backup snapshot")]
[assembly: SuppressMessage("Security", "CA2100", Justification = "Internal staging database backup snapshot")]
[assembly: SuppressMessage("roslyn", "CA2100", Justification = "Internal staging database backup snapshot")]
