<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common\Seedarr.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BencodeNET" Version="4.0.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FluentMigrator.Runner" Version="6.2.0" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="6.2.0" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="6.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Open.NAT" Version="2.1.0" NoWarn="NU1701" />
    <PackageReference Include="Polly" Version="8.5.2" />
  </ItemGroup>
</Project>
