<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);SA1501;SA1502;SA1503;SA1315;SA1316;SA1515;IDE0005</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="4.47.0" />
    <PackageReference Include="Selenium.Support" Version="4.47.0" />
  </ItemGroup>
</Project>
