namespace NzbDrone.Core.Automation;

public enum AutomationTrigger
{
    TorrentAdded = 0,
    TorrentCompleted = 1,
    RatioReached = 2,
    TorrentError = 3,
    Manual = 4,
    Scheduled = 5,
    TorrentDeleted = 6,
    TorrentStatusChanged = 7,
    MediaEnriched = 8,
    ArchiveExtracted = 9,
    ExtractionFailed = 10,
    VpnDisconnected = 11,
    VpnRestored = 12,
    HealthRestored = 13,
    CategoryChanged = 14,
    ApplicationStarted = 15,
    TorrentStarted = 16,
    TorrentPaused = 17,
    TorrentStalled = 18,
    SeedingTimeReached = 19,
    HashCheckCompleted = 20,
    ProgressMilestone = 21,
    SpeedThresholdExceeded = 22,
    SpeedThresholdDropped = 23,
    BandwidthQuotaApproaching = 24,
    PortForwardingFailed = 25,
    PeerBanned = 26,
    TrackerUnreachable = 27,
    TrackerBoostApplied = 28,
    DiskSpaceLow = 29,
    DiskSpaceCritical = 30,
    FileMoveFailed = 31,
    MediaInspectionFailed = 32,
    ArrImportCompleted = 33,
    ApplicationUpdated = 34,
    BackupCompleted = 35,
    BackupFailed = 36,
    TaskFailed = 37,
    TorrentStallResolved = 38,
}
