<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AnalysisLevel>6.0-all</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NuGetAuditLevel>critical</NuGetAuditLevel>

    <SeedarrRootDir>$(MSBuildThisFileDirectory)..\</SeedarrRootDir>

    <SeedarrProject>false</SeedarrProject>
    <SeedarrProject Condition="$(MSBuildProjectName.StartsWith('Seedarr'))">true</SeedarrProject>
    <SeedarrProject Condition="$(MSBuildProjectName.StartsWith('NzbDrone'))">true</SeedarrProject>

    <TestProject>false</TestProject>
    <TestProject Condition="$(MSBuildProjectName.EndsWith('.Test'))">true</TestProject>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;SA1200</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Configuration Condition="'$(Configuration)'==''">Release</Configuration>
    <BaseIntermediateOutputPath>$(SeedarrRootDir)_temp\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(SeedarrRootDir)_temp\obj\$(MSBuildProjectName)\$(Configuration)\</IntermediateOutputPath>
    <OutputPath>$(SeedarrRootDir)_temp\bin\$(Configuration)\$(MSBuildProjectName)\</OutputPath>
    <OutputPath Condition="'$(SeedarrProject)'=='true'">$(SeedarrRootDir)_output\</OutputPath>
    <OutputPath Condition="'$(TestProject)'=='true'">$(SeedarrRootDir)_tests\</OutputPath>
    <EnableBaseIntermediateOutputPathMismatchWarning>false</EnableBaseIntermediateOutputPathMismatchWarning>
    <BaseIntermediateOutputPath>$([MSBuild]::MakeRelative('$(MSBuildProjectDirectory)', '$(BaseIntermediateOutputPath)'))</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$([MSBuild]::MakeRelative('$(MSBuildProjectDirectory)', '$(IntermediateOutputPath)'))</IntermediateOutputPath>
    <OutputPath>$([MSBuild]::MakeRelative('$(MSBuildProjectDirectory)', '$(OutputPath)'))</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SeedarrProject)'=='true'">
    <Product>Seedarr</Product>
    <Company>seedarr</Company>
    <PackageProjectUrl>https://www.seedarr.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dmzoneill/Seedarr</RepositoryUrl>
    <AssemblyVersion>1.0.0.*</AssemblyVersion>
    <AssemblyConfiguration>$(Configuration)-dev</AssemblyConfiguration>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <Deterministic Condition="$(AssemblyVersion.EndsWith('*'))">False</Deterministic>
  </PropertyGroup>

  <PropertyGroup>
    <_DirName>$([System.IO.Path]::GetFileName($(MSBuildProjectDirectory)))</_DirName>
    <RootNamespace>$(_DirName)</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SeedarrProject)'=='true' and '$(EnableAnalyzers)'=='false'">
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup Condition="'$(SeedarrProject)'=='true' and '$(EnableAnalyzers)'!='false'">
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <AdditionalFiles Include="$(SolutionDir)stylecop.json" />
  </ItemGroup>

  <ItemGroup Condition="'$(TestProject)'=='true'">
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>
</Project>
