---
name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: [refresh]

permissions: write-all

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      basic: "true"
      test-ready: "true"
      dotnet: "true"
      dotnet-version: "10.0.x"
      docker-build: "true"
      container-file: "Containerfile"
      VALIDATE_JSCPD: "false"
      VALIDATE_BIOME_FORMAT: "false"
      VALIDATE_BIOME_LINT: "false"
      VALIDATE_GITHUB_ACTIONS_ZIZMOR: "false"
      VALIDATE_TSX: "false"
