---
name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: [refresh]

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  issues: write
  pull-requests: write
  security-events: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      basic: "true"
      test-ready: "true"
      dotnet: "true"
      dotnet-version: "10.0.x"
      docker-build: "true"
      container-file: "Containerfile"
      VALIDATE_JSCPD: "false"
      VALIDATE_BIOME_FORMAT: "false"
      VALIDATE_BIOME_LINT: "false"
      VALIDATE_GITHUB_ACTIONS_ZIZMOR: "false"
      VALIDATE_TSX: "false"
      VALIDATE_TYPESCRIPT_ES: "false"
      VALIDATE_MARKDOWN: "true"
      VALIDATE_NATURAL_LANGUAGE: "false"
      VALIDATE_DOCKERFILE_HADOLINT: "true"
      VALIDATE_EDITORCONFIG: "true"
      VALIDATE_BASH: "true"
      VALIDATE_SHELL_SHFMT: "true"
      VALIDATE_CSS: "true"
      VALIDATE_GITLEAKS: "true"
      VALIDATE_JAVASCRIPT_ES: "false"
      VALIDATE_JSON: "true"
      VALIDATE_PYTHON: "false"
      VALIDATE_PYTHON_BLACK: "false"
      VALIDATE_PYTHON_PYLINT: "false"
      VALIDATE_PYTHON_FLAKE8: "false"
      VALIDATE_PYTHON_ISORT: "false"
      VALIDATE_PYTHON_MYPY: "false"

